Docs/ata quinta time
mdsreq-fga-unb/2024.2-T03-CafeDoSitio pull request #29
Opened 2024-11-08 03:21 UTC by DanielRogs

## Descrição

Este Pull Request acompanha a ata da reunião realizada na Quinta-Feira em time, às 19h30.

## _Issue_ Relacionada

closes #28 

## Como Isso Foi Testado?

A documentação foi executada com `mkdocs serve` e não houve presença de bugs ou quebra do código.

## Capturas de Tela (se apropriado):

![image](https://github.com/user-attachments/assets/d60b5895-d837-4609-bfe7-0d4e0eb0f18d)

![image](https://github.com/user-attachments/assets/2c7cf6ba-9e3a-494f-a656-f18c70a6d672)

## Tipos de Mudanças

- [ ] **FEATURE |** Este Pull Request trata-se de uma nova funcionalidade para o sistema, _SEM interferir as funcionalidade já existentes_.
- [ ] **FEATURE DISRUPTIVA:  |** Este Pull Request trata-se de uma _correção ou adição de uma funcionalidade que AFETOU ou MUDOU alguma funcionalidade existente_.
- [ ] **HOTFIX  |** Este Pull Request trata-se de uma correção de uma _issue_, _mas que NÃO altera as funcionalidade já existentes_.
- [ ] **RELEASE  |** Este Pull Request trata-se de uma release para a Branch Main, isto é, uma _nova versão estável para a ramificação principal_.
- [x] **DOCUMENTATION  |** Este Pull Request trata-se SOMENTE de adições à documentação do Projeto.

2024-11-08 03:23 UTC, DanielRogs commented
!!!
NÃO dar MERGE antes do PR #27, pfv

2024-11-08 07:32 UTC, JoaoODragonborn requested changes

2024-11-08 07:32 UTC, JoaoODragonborn commented on docs/sections/2-docPage/4-cronogramaEntregas.md
> +06/11/2024 | 1.0 | Criação do Documento e Adição do Tópico 4 | Daniel Rodrigues |
Esqueceu de colocar o revisor.

2024-11-08 16:07 UTC, DanielRogs commented on docs/sections/2-docPage/4-cronogramaEntregas.md
> +06/11/2024 | 1.0 | Criação do Documento e Adição do Tópico 4 | Daniel Rodrigues |
Oxe, mals kkk. Eu até escrevi, mas esqueci de dar Push

2024-11-08 16:07 UTC, DanielRogs commented on docs/sections/2-docPage/4-cronogramaEntregas.md
> +06/11/2024 | 1.0 | Criação do Documento e Adição do Tópico 4 | Daniel Rodrigues |
Vle o Aviso

2024-11-08 17:20 UTC, DanielRogs commented
@JoaoODragonborn, prontinho man. Fiz a correção

2024-11-10 01:17 UTC, JoaoODragonborn approved these changes

2024-11-10 01:17 UTC, merged