[DOC]: Figuras
mdsreq-fga-unb/2024.2-T03-CafeDoSitio pull request #50
Opened 2024-11-15 16:53 UTC by JoaoODragonborn

## Descrição

Melhoria na resolução/legibilidade das imagens
## _Issue_ Relacionada

closes #45 

## Como Isso Foi Testado?

Foi realizado uma inspeção visual através da execução local do MkDocs versão 1.6.1 com mkdocs-material, que utiliza o Python na versão 3.10, no sistema operacional POP! OS através do comando "mkdocs serve" na pasta raiz do repositório.
## Capturas de Tela (se apropriado):
![Screenshot from 2024-11-15 13-48-51](https://github.com/user-attachments/assets/4078dda4-16a3-4f1e-988c-fd89fe9bca98)
![Screenshot from 2024-11-15 13-48-42](https://github.com/user-attachments/assets/183bdecd-57ec-4997-ae66-f11d09eb46ee)
![Screenshot from 2024-11-15 13-48-29](https://github.com/user-attachments/assets/7295815e-505f-4baa-8128-7943d33b268e)

## Tipos de Mudanças

- [ ] **FEATURE |** Este Pull Request trata-se de uma nova funcionalidade para o sistema, _SEM interferir as funcionalidade já existentes_.
- [ ] **FEATURE DISRUPTIVA:  |** Este Pull Request trata-se de uma _correção ou adição de uma funcionalidade que AFETOU ou MUDOU alguma funcionalidade existente_.
- [ ] **HOTFIX  |** Este Pull Request trata-se de uma correção de uma _issue_, _mas que NÃO altera as funcionalidade já existentes_.
- [ ] **RELEASE  |** Este Pull Request trata-se de uma release para a Branch Main, isto é, uma _nova versão estável para a ramificação principal_.
- [x] **DOCUMENTATION  |** Este Pull Request trata-se SOMENTE de adições à documentação do Projeto.

2024-11-15 16:54 UTC, JoaoODragonborn commented
reconheço que não está tão bonito, mas acredito ter melhorado a legibilidade/"resolução".

2024-11-16 22:29 UTC, DanielRogs requested changes
No mais, o resto está perfeito! Realmente as figuras ficaram mais visíveis.

2024-11-16 22:29 UTC, DanielRogs commented on docs/sections/2-docPage/2-solucaoProposta.md
> +Tabela 1.1 - Conhecimentos quantificados da equipe em linguagens e front-end
Necessário ajustar as referência à estas figuras dentro do texto, como por exemplo, na linha 66:

```
 tal como é ilustrado na Figura 1, nas parte de frameworks de Front-End.
```

Poderia ser:

```
 tal como é ilustrado na Figura 1.1, seção de frameworks do Front-End.
```

E colocar na linha 68 uma referência à Figura 1.2, da parte de Backend:

```
Já para a parte do Back-end, será utilizado as ferramentas consideradas fáceis para a curva de aprendizagem, visto que grande parte da equipe não possui experiências com essa área, como visto na Figura 1.2. [...]
```

2024-11-18 16:39 UTC, DanielRogs approved these changes
LGTM🚀

2024-11-18 16:40 UTC, merged