fix: corrigindo tópico objetivos
mdsreq-fga-unb/2024.2-T03-CafeDoSitio pull request #52
Opened 2024-11-16 19:45 UTC by marcellaanderle

## Descrição
Corrigindo o tópico objetivos que está na seção Solução proposta.

## _Issue_ Relacionada

[](https://github.com/mdsreq-fga-unb/2024.2-T03-CafeDoSitio/issues/46)
[DOC]: Objetivos 
closes #46

## Como Isso Foi Testado?
Teste realizado com visualização do makdocs serve

## Capturas de Tela (se apropriado):
![image](https://github.com/user-attachments/assets/d71af399-b75f-4bf2-b9a0-6324658259c2)

## Tipos de Mudanças

- [ ] **FEATURE |** Este Pull Request trata-se de uma nova funcionalidade para o sistema, _SEM interferir as funcionalidade já existentes_.
- [ ] **FEATURE DISRUPTIVA:  |** Este Pull Request trata-se de uma _correção ou adição de uma funcionalidade que AFETOU ou MUDOU alguma funcionalidade existente_.
- [ ] **HOTFIX  |** Este Pull Request trata-se de uma correção de uma _issue_, _mas que NÃO altera as funcionalidade já existentes_.
- [ ] **RELEASE  |** Este Pull Request trata-se de uma release para a Branch Main, isto é, uma _nova versão estável para a ramificação principal_.
- [x] **DOCUMENTATION  |** Este Pull Request trata-se SOMENTE de adições à documentação do Projeto.

2024-11-16 22:50 UTC, DanielRogs requested changes
Acho interessante deixar mais claro que o software irá resolver o problema de acesso às informações da Empresa, como definimos no Diagrama de Ishikawa.

Fiz uma sugestão abaixo de como o parágrafo pode ficar. Dessa maneira damos mais foco ao problema da Família do Sítio, e não à uma funcionalidade como a Ouvidoria, como você tinha escrito. 

Em resumo, o objetivo do software não é fazer um sistema web, nem fazer um blog, nem ouvidoria, nem nada disso. Na realidade o objetivo do software é **Promover maior acesso às informações da Família do Sítio**, POR MEIO de uma solução web, blogs, ouvidoria, etc. Sacou?

2024-11-16 22:50 UTC, DanielRogs commented on docs/sections/2-docPage/2-solucaoProposta.md
> +O principal objetivo deste software é ampliar as opções de interação dos clientes com os serviços oferecidos pelo Café do Sítio, contribuindo para a manutenção de uma boa reputação da empresa ao prop
```suggestion
Primordialmente, o principal objetivo deste software é facilitar o acesso às informações institucionais e de Atendimento da Família do Sítio para os Usuários. Este objetivo será alcançado com a resolução das 5 Causas indicadas no Diagrama espinha de peixe, presente na Figura 1 da seção [Cenário Atual do Cliente e Negócio](./1-cenarioAtual.md):

1. Blogs;
2. Visitas Técnicas;
3. Recrutamento;
4. Institucional;
5. Ouvidoria.

As causas acima foram identificadas como solucionáveis dentro de um produto de software. Com uma unificação dos serviços requeridos e do direcionamento dos feedbacks, é esperado que haja um fluxo melhor de informações, certificando-se de que elas cheguem onde devem chegar.
```

2024-11-16 22:53 UTC, DanielRogs commented
Outra coisa importante também: Resolver os conflitos da sua Branch com a `mainDoc`, blz?

Não podemos dar merge sem a correção dos conflitos. Só dar o comando: `git pull origin mainDoc` dentro da sua ramificação, que você está construindo essa funcionalidade. O VsCode irá apontar para você os conflitos, só resolvê-los.

2024-11-16 22:59 UTC, DanielRogs commented on docs/sections/2-docPage/2-solucaoProposta.md
> +O principal objetivo deste software é ampliar as opções de interação dos clientes com os serviços oferecidos pelo Café do Sítio, contribuindo para a manutenção de uma boa reputação da empresa ao prop
Uma dica. Tem como você commitar sem nem acessar o VSCode. Só clicar no botão "commit sugestion" aí em cima para subtituir com as minhas sugestões.

Só apague a mensagem de commit para o protocolo correto que estamos seguindo, o conventional commits:
`docs: corrigindo topico 2.1`

2024-11-18 17:12 UTC, manuvaladares approved these changes
Ficou ótimo!

2024-11-18 17:37 UTC, DanielRogs approved these changes
LGTM!

2024-11-18 17:37 UTC, merged