[DOC]: Realizar tópico 4.1 da Documentação no GitPages
mdsreq-fga-unb/2024.2-T03-CafeDoSitio pull request #92
Opened 2024-12-04 21:47 UTC by manuvaladares

## Descrição
Criação da página de Engenharia de Requisitos com a adição do tópico 4.1 da documentação. 

## _Issue_ Relacionada

closes #77 

## Como Isso Foi Testado?
Foi testado durante o desenvolvimento através do mkdocs serve. Essa abordagem consistiu em verificar a interface implementada, observando a exibição correta dos elementos e a resposta esperada.

## Capturas de Tela (se apropriado):
![image](https://github.com/user-attachments/assets/8b15d86e-52ce-447e-af38-a2eb3ca701a6)

## Tipos de Mudanças

- [ ] **FEATURE |** Este Pull Request trata-se de uma nova funcionalidade para o sistema, _SEM interferir as funcionalidade já existentes_.
- [ ] **FEATURE DISRUPTIVA:  |** Este Pull Request trata-se de uma _correção ou adição de uma funcionalidade que AFETOU ou MUDOU alguma funcionalidade existente_.
- [ ] **HOTFIX  |** Este Pull Request trata-se de uma correção de uma _issue_, _mas que NÃO altera as funcionalidade já existentes_.
- [ ] **RELEASE  |** Este Pull Request trata-se de uma release para a Branch Main, isto é, uma _nova versão estável para a ramificação principal_.
- [x] **DOCUMENTATION  |** Este Pull Request trata-se SOMENTE de adições à documentação do Projeto.

2024-12-06 02:29 UTC, JoaoODragonborn requested changes

2024-12-06 02:29 UTC, JoaoODragonborn commented on docs/sections/2-docPage/4-engenhariaRequisitos.md
> +**Análise de risco:** É utilizada para identificar os requisitos que podem apresentar riscos ou iviabilizar o produto ou solução, e assim obter formas de reduzir o risco. Na proposta, a análise de ri
"iviablizar" -> "inviabilizar"

2024-12-06 02:29 UTC, JoaoODragonborn commented on docs/sections/2-docPage/4-engenhariaRequisitos.md
> +**Critérios de aceitação:** São definidos critérios de aceitação, ou seja, é acordado junto com os stakeholders do projeto e o Project Owner o que uma User Story precisa ter para ser aceita. Sendo is
"Sendo isso feito para que para que ambas as partes"
"para que" na frase está duplicado.

2024-12-08 19:48 UTC, arthur-suares commented
Correções feitas!

2024-12-09 12:55 UTC, JoaoODragonborn approved these changes

2024-12-09 12:55 UTC, merged